#stage 1 (build stage) - use to build the packages and app
FROM node:24 as builder

WORKDIR /app

COPY . .

#install the packages
RUN npm install

#creates a folder called /dist
RUN npm run build

#end of stage 1

#stage 2 (runner stage) - used to run the application from the build stage
FROM node:24-alpine AS runner

WORKDIR /app

COPY package.json .

RUN npm install -g vite

COPY --from=builder /app/dist ./dist

CMD ["npm","run","preview", "--", "--host", "0.0.0.0", "--port", "4173"]
